---
title: "Environmental Bias Report"
output: html_document
params:
  n_breaks: 50
  periods: NULL
  env_var_column: NULL
  crs: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages}
library(dplyr)
library(ggplot2)
library(patchwork)
library(sf)

# install remotes to install occAssess
if(!require(remotes)){
  install.packages(remotes)
}

if(!require(occAssess)){
  install_github("robboyd/occAssess")
}

```

## Input Parameters

- **Number of Breaks**: `r params$n_breaks`
- **Periods (Note: This is a list object)**: `r paste(sapply(params$periods, function(p) paste(range(p), collapse = "-")), collapse = ", ")`
- **Environmental Variable**: `r params$env_var_column`
- **crs**: `r params$crs`

```{r load-data}
data <- read.csv("export/your_formatted_data.csv")

# NOTE: The aux_file is very large and so we load it directly as an rds file rather than a csv
aux_file <- readRDS("export/aux_file.rds")
```

```{r map-to-monads}
convert_x_coordinate_y_coordinate_to_monad  <- function(x_coordinate, y_coordinate, crs) {

  # Convert to OSGB36 eastings/northings if coordinates are lat/lon
  crs_obj <- st_crs(crs)

  if (crs_obj$IsGeographic) {
    coords_sf <- st_as_sf(data.frame(lon = x_coordinate, lat = y_coordinate),
                          coords = c("lon", "lat"),
                          crs = crs)
    coords_osgb <- st_transform(coords_sf, 27700)
    xy <- st_coordinates(coords_osgb)
    x_coordinate <- xy[, "X"]
    y_coordinate <- xy[, "Y"]
  }

  # OSGB 100k grid letter lookup (A-Z, skipping I)
  grid_letters <- matrix(LETTERS[-9], ncol = 5, byrow = TRUE)[5:1, ]

  # First letter: 500 km grid square
  xo_500 <- trunc(x_coordinate / 500000) + 3
  yo_500 <- trunc(y_coordinate / 500000) + 2
  s1 <- grid_letters[cbind(yo_500, xo_500)]

  # Second letter: 100 km grid square
  xo_100 <- trunc((x_coordinate %% 500000) / 100000) + 1
  yo_100 <- trunc((y_coordinate %% 500000) / 100000) + 1
  s2 <- grid_letters[cbind(yo_100, xo_100)]

  # Numeric part: 1 km square (monad)
  monad_e <- trunc((x_coordinate %% 100000) / 1000)
  monad_n <- trunc((y_coordinate %% 100000) / 1000)

  # Combine into full monad code
  monads <- paste0(s1, s2, sprintf("%02d%02d", monad_e, monad_n))
  return(monads)
}

data <- data %>%
  mutate(monad = convert_x_coordinate_y_coordinate_to_monad(x_coordinate, y_coordinate, crs = params$crs))
```

```{r prepare-env-data}
positions <- data %>%
  dplyr::select(monad, year)

env_data <- aux_file %>%
  filter(auxcolumn == params$env_var_column) %>%
  dplyr::select(monad, value) %>%
  rename(!!params$env_var_column := value)

for (i in seq_along(params$periods)) {
  years <- params$periods[[i]]
  monads_in_period <- positions %>%
    filter(year %in% years) %>%
    distinct(monad) %>%
    pull(monad)

  colname <- paste0("presence_", i)
  env_data[[colname]] <- ifelse(env_data$monad %in% monads_in_period, 1, 0)
}
```

```{r plot-env-bias}
# Run assessBias1D and store both plot and data
results <- lapply(seq_along(params$periods), function(i) {
  result <- assessBias1D(
    pop = env_data,
    breaks = params$n_breaks,
    R = paste0("presence_", i),
    x = params$env_var_column,
    RNames = paste0("Period ", i)
  )
  list(
    plot = result$plot,
    data = result$data %>% dplyr::mutate(period = paste0("Period ", i))
  )
})

# Extract and combine all data frames
combined_data <- do.call(rbind, lapply(results, `[[`, "data"))

# Save to a csv file
write.csv(combined_data, file = "export/environmental_bias.csv", row.names = FALSE)

# Extract just the ggplot objects
plots <- lapply(results, `[[`, "plot")

# View the plots
wrap_plots(plots, ncol = 1)
```